version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: docker

  spring-boot-app1:
      build:
        context: ./spring-boot-app
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/docker
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 1234
  react-app:
      build:
        context: ../sshkey
        dockerfile: Dockerfile
      ports:
        - "3000:3000"